### ISSUE TITLE
DesignFrame

### ISSUE THREAD

**Issue by trymkb** [jthanto/ez-blog#1]
Hvis du kaller filen for **MY_**DesignFrame.php så vil den autoloade ;-)

/*
|--------------------------------------------------------------------------
| Class Extension Prefix
|--------------------------------------------------------------------------
|
| This item allows you to set the filename/classname prefix when extending
| native libraries.  For more information please see the user guide:
|
| http://codeigniter.com/user_guide/general/core_classes.html
| http://codeigniter.com/user_guide/general/creating_libraries.html
|
*/
$config['subclass_prefix'] = 'MY_';

**Comment by jthanto** [comment]
Nice! Didn't know =]
Blir nok å se mer på dette i nær fremtid =]

**Comment by jthanto** [comment]
Endte med å endre navnet til MY_Controller, sånn siden det bare er en extension av CI_Controller og egentlig skal brukes på samme måte. It worked! Prøvde også å lukke issuet via comittmeldinga, men det gikk heller dårlig. Lukker uansett denne. :)
